### ISSUE TITLE
why not publish this on chrome store?

### ISSUE THREAD

**Issue by capaj** [GMaiolo/remove-w3schools#1]
you probably need a dev account for that right? I might have it-would it be okay for me to publish this from my account?

**Comment by GMaiolo** [comment]
I'm going to take a look into it tonight, not sure if it's clean enough yet to publish it to the store though.

**Comment by GMaiolo** [comment]
@capaj [Here we go, thanks!](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje) If you want any improvements don't hesitate to open another issue or send a pull request.
