### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by pmnord** [GMaiolo/remove-w3schools#14]
I'm getting w3schools links in my google search results again

**Comment by GMaiolo** [comment]
@pmnord Just updated the selector, once Google approves the extension update it should be working normally again

**Comment by samwinslow** [comment]
+1 that this is not working for me either. I used to have this on a different computer years ago and loved it, so thank you! Now I find myself looking up simple CSS things almost every day and the useless W3Schools is there again.

**Comment by GMaiolo** [comment]
@samwinslow seems that something else changed now, I'll investigate tomorrow and hopefully fix it!

**Comment by GMaiolo** [comment]
@samwinslow Just updated the extension to version 3.0.23 (it'll take a day at most to update as Google needs to approve it)
Hope it fixes it, let me know if it does once it updates!
