### ISSUE TITLE
Not working as of Nov 28

### ISSUE THREAD

**Issue by sam-candeocreative** [GMaiolo/remove-w3schools#2]
W3 Schools showing up in google search results for me again.

Noticed on searches for some CSS things such as "css multi-column".

Extension is up to date, and I've double checked that it is enabled.

**Comment by GMaiolo** [comment]
Working on this, will update the extension tonight.

**Comment by GMaiolo** [comment]
Hey @sam-candeocreative there's a [new version up](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje)! Please tell me if the problem got solved.

**Comment by sam-candeocreative** [comment]
@GMaiolo Unfortunately still not working on v3.0

Search I tried to test (shows w3schools first, then MDN):
![image](https://cloud.githubusercontent.com/assets/17708766/20843419/ec132ece-b880-11e6-855f-4d49ab8dfa14.png)

Let me know if there's any other details I can provide to help debug.

**Comment by GMaiolo** [comment]
I'm performing that same query and I get 2 results deleted.
What's your OS and Chrome version?

Do you see the icon grayed out, or with a number like this: 
![2016-12-02_1623](https://cloud.githubusercontent.com/assets/9776436/20847167/aaa08dc6-b8ab-11e6-859a-68e47fa05000.png)

What does the console says? There should be something like this: 
![2016-12-02_1625](https://cloud.githubusercontent.com/assets/9776436/20847232/f4a6caa2-b8ab-11e6-8b76-d20bfb24469a.png)

If the common console is displaying the value to eliminate correctly, what does the extension's console says (should be empty): 
![2016-12-02_1634](https://cloud.githubusercontent.com/assets/9776436/20847526/4ea50f0e-b8ad-11e6-8239-1a1b14352eae.png)

What country is the google search engine redirecting you (google.com.[country])? I may have missed it.

As soon as you are able to answer I'll take a deeper look and upload a 3.0.1 version when I find the problem, meanwhile I'm testing the extension in other devices/OSs.

Sorry for the trouble @sam-candeocreative, hope we get this fixed soon.

**Comment by sam-candeocreative** [comment]
I am US based, and getting the US/EN google. 

Nothing happening for me both from search bar in chrome or direct google.com search (resulting in URL https://www.google.com/#q=css+column+count for example)

Chrome: Version 55.0.2883.75 m
Win10 V1607 OS Build 14393.447

**Comment by GMaiolo** [comment]
@sam-candeocreative, should be working now [in v3.0.1](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje). Mind to check?
The extension used to triggered only when google's pathname was `'/search'`, but your queries found another valid pathname, which is the basic `'/'`, pretty hard to spot!

Hope it is fixed by now, I'm waiting for your response.

**Comment by 1egoman** [comment]
Not working for me either. My search link is `https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=w3schools`, and with the extension installed it's exactly the same:

<img width="988" alt="screen shot 2016-12-05 at 7 40 02 am" src="https://cloud.githubusercontent.com/assets/1704236/20885292/11c7c58c-babe-11e6-92e0-4e144900e2b4.png">

The icon looks like this on the above page:
<img width="36" alt="screen shot 2016-12-05 at 7 41 48 am" src="https://cloud.githubusercontent.com/assets/1704236/20885344/51817d94-babe-11e6-9038-941d689f8554.png">

On a hunch, I manually went to the address `https://www.google.com/search?q=w3schools`. That time, the first w3schools entry from the above google page screenshot was successfully removed,  and the icon was red in color.

My theory is that the extension is too strict on the pages it runs on ([code here](https://github.com/GMaiolo/remove-w3schools/blob/master/scripts/remover.js#L18)).

**Comment by GMaiolo** [comment]
@1egoman you've hit the nail. 
In the first link you are sent to yet another google pathname: `/webhp`. Even though I get instantly redirected to `https://www.google.com/search?q=w3schools&rct=j` when accessing it, and the extension works for me there, you seem not to get redirected.

At this point I think that relying on google's possible pathnames during searches is a bit too broad, as you both demonstrated that there are many varieties.
I'll research a little for the most performant solution to avoid execution in pages that don't need to and probably get a new build up by tonight.

**Comment by GMaiolo** [comment]
And by saying _"probably get a new build up by tonight"_ I meant now. 
@sam-candeocreative && @1egoman, would you both mind to update and check [v3.0.11](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje)? 
I'm exactly 0.03% sure that this is completely fixed now for you guys.

I'm on hold until I get your feedback.

**Comment by 1egoman** [comment]
@GMaiolo Works for me! Thanks!

Also, there's another small issue that I found. https://github.com/GMaiolo/remove-w3schools/issues/3

**Comment by GMaiolo** [comment]
Great, waiting for @sam-candeocreative, as soon as you confirm it's solved I will close the issue.

**Comment by GMaiolo** [comment]
As there's no answer I'll assume it's fixed. Please open another issue if it happens again and thanks for the collaboration.
