### ISSUE TITLE
Link spacing is changed when links are removed

### ISSUE THREAD

**Issue by 1egoman** [GMaiolo/remove-w3schools#3]
All the margins from the elements that are removed remain, probably because their containers are still on the page.

Spacing when not removed:
<img width="745" alt="screen shot 2016-12-05 at 10 25 55 am" src="https://cloud.githubusercontent.com/assets/1704236/20890536/3e6fa354-bad5-11e6-9e51-258ccf89545a.png">

Spacing when removed:
<img width="725" alt="screen shot 2016-12-05 at 10 24 13 am" src="https://cloud.githubusercontent.com/assets/1704236/20890501/1e5a9c4a-bad5-11e6-812e-98fa11704179.png">

**Comment by GMaiolo** [comment]
Should be solved in [v3.0.12](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje), along with some performance boosts.

**Comment by GMaiolo** [comment]
@1egoman could you confirm it's fixed?

**Comment by 1egoman** [comment]
@GMaiolo Looks to be fixed!

**Comment by GMaiolo** [comment]
No problem, if you've got any other problem/suggestion open a new issue and we'll check it!
