### ISSUE TITLE
bg.js tabsManager.imagePaths needs a set for get_tId_and_wId

### ISSUE THREAD

**Issue by hcgernhardtiii** [GMaiolo/remove-w3schools#8]
Error condition is chrome.browserAction.setIcon in bg.js.  Chrome doesn't like it when the event is get_tId_and_wId, which doesn't have an icon set.  Fixed it by duplicating one of the icon sets and keying it with get_tId_and_wId.

**Comment by GMaiolo** [comment]
Fixed in [v3.0.20](https://github.com/GMaiolo/remove-w3schools/releases/tag/3.0.20) (also updated in [the Chrome Store](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje)), thanks @hcgernhardtiii 👍
