### ISSUE TITLE
Doesn't remove W3School links; Can't read property tId of undefined

### ISSUE THREAD

**Issue by akosipax** [GMaiolo/remove-w3schools#9]
I checked the console and this is what's spitting out. It's a different error message from #8.

```
Error handling response: TypeError: Cannot read property 'tId' of undefined
    at Object.<anonymous> (chrome-extension://gohnadkcefpdhblajddfnhapimpdjkje/scripts/remover.js:28:32)
```

**Comment by GMaiolo** [comment]
Fixed in [v3.0.20](https://github.com/GMaiolo/remove-w3schools/releases/tag/3.0.20) (also updated in [the Chrome Store](https://chrome.google.com/webstore/detail/remove-w3schools/gohnadkcefpdhblajddfnhapimpdjkje)), thanks @akosipax 👍
